name: Publish site
on:
  push:
    branches:
      - main
jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i
      - run: npm run build-prod
      - run: echo -n "" > dist/.nojekyll
      - run: git clone https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git ghpages -b gh-pages --depth 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Clone gh-pages branch
      - run: |
          git rm *
          cp -r ../dist/. .
          git add *
        working-directory: ./ghpages
        name: Copy new build
      - run: git commit -m "Updates"
        working-directory: ./ghpages
        env:
          GIT_AUTHOR_EMAIL: support+actions@github.com
          GIT_AUTHOR_NAME: github-actions-bot
        name: Commit new version
      - run: git push origin gh-pages
        working-directory: ./ghpages
        name: Push version