name: Publish site
on:
  push:
    branches:
      - main
jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i
      - run: npm run build-prod
      - run: echo -n "" > dist/.nojekyll
      - run: |
          git clone https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git ghpages -b gh-pages --depth 1
          cd ghpages
          git rm *
          cp -r ../dist/. .
          git add *
          git commit -m "Updates" --author "github-actions-bot <support+actions@github.com>"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
